server:
  port: 9511

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8970/eureka/
  
spring:
  application:
    name: jeesite-cloud-admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  config: classpath:config/logback-spring.xml