
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8970/eureka/

spring:
  application:
    name: jeesite-cloud-zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false
        
logging:
  config: classpath:config/logback-spring.xml