spring:
  application:
    name: jeesite-cloud-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9511

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8970/eureka/