
#productName: JeeSite Core

#======================================#
#========= Framework settings =========#
#======================================#

# Web 相关
web:
  
  # 核心模块的Web功能（仅作为微服务时设为false）
  core: 
    enabled: true
    
#======================================#
#========== Project settings ==========#
#======================================#
